spring.application.name=PGmanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/pgman
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# THE NEW KEY YOU MUST ADD
jwt.secret=8BADDAB00FACEB00KCAFED00D900DF00D8BADDAB00FACEB00KCAFED00D900DF00D

jwt.refresh-token.expiration=2592000000 

#### Expiration for the long-lived refresh token (e.g., 30 days in milliseconds)
#jwt.secret=${JWT_SECRET}
#
#spring.application.name=PGmanagement
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#server.port=${PORT:8080}