spring.application.name=PGmanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/pgman
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080



## Application name
#spring.application.name=PGmanagement
##
### PostgreSQL connection (Render provides these via Environment Variables)
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
##
### JPA & Hibernate setup
#spring.jpa.hibernate.ddl-auto=update
##spring.jpa.show-sql=true
###spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
##
## Server port (Render will inject dynamically)
#server.port=${PORT:8080}